#################################
# RPM-specific Makefile		#
#################################

# Predefined values

ARCH=`rpm --eval "%{_arch}"`
DIR=`pwd`
DIST=.rhel7
SPECFILE="points2grid.spec"

# Now, include global Makefile
include ../../../common/Makefile.global
