#################################
# RPM-specific Makefile		#
#################################

# Predefined values

ARCH=`rpm --eval "%{_arch}"`
DIR=`pwd`
DIST=.f21
SPECFILE="hexer.spec"

# Now, include global Makefile
include ../../../common/Makefile.global
